"""addOrderForPageTaskList

Revision ID: 0b241cb71c86
Revises: 1a0970ae24fd
Create Date: 2025-05-12 03:49:52.806244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b241cb71c86'
down_revision = '1a0970ae24fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('OrderIndex', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.drop_column('OrderIndex')

    # ### end Alembic commands ###
