"""addOrderForImageAndNote

Revision ID: 1a0970ae24fd
Revises: ec5696a2261f
Create Date: 2025-05-12 02:48:31.301782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a0970ae24fd'
down_revision = 'ec5696a2261f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('OrderIndex', sa.Integer(), nullable=True))

    with op.batch_alter_table('textbox', schema=None) as batch_op:
        batch_op.add_column(sa.Column('OrderIndex', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('textbox', schema=None) as batch_op:
        batch_op.drop_column('OrderIndex')

    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.drop_column('OrderIndex')

    # ### end Alembic commands ###
