"""addCardPostion

Revision ID: 2416717e32e6
Revises: 5281dd1c3c25
Create Date: 2025-05-11 19:59:47.624646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2416717e32e6'
down_revision = '5281dd1c3c25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('X', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('Y', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.drop_column('Y')
        batch_op.drop_column('X')

    # ### end Alembic commands ###
