"""add_color_field_to_events

Revision ID: 2ec37de23a3e
Revises: 74329b6c6b82
Create Date: 2025-07-23 23:22:23.487742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ec37de23a3e'
down_revision = '74329b6c6b82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Color', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('Color')

    # ### end Alembic commands ###
