"""extend Collaboration with FolderId, WorkspaceId, FileId

Revision ID: 3e6652213aba
Revises: ba2d43bedb48
Create Date: 2025-04-12 12:49:03.872144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e6652213aba'
down_revision = 'ba2d43bedb48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collaborations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('FolderId', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('WorkspaceId', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('FileId', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'workspaces', ['WorkspaceId'], ['Id'])
        batch_op.create_foreign_key(None, 'folders', ['FolderId'], ['Id'])
        batch_op.create_foreign_key(None, 'files', ['FileId'], ['Id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collaborations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('FileId')
        batch_op.drop_column('WorkspaceId')
        batch_op.drop_column('FolderId')

    # ### end Alembic commands ###
