"""initial migration

Revision ID: 5195c1c8bf1a
Revises: 
Create Date: 2025-04-12 12:22:23.322362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5195c1c8bf1a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(), nullable=True),
    sa.Column('ApplicationId', sa.String(), nullable=True),
    sa.Column('TenantId', sa.String(), nullable=True),
    sa.Column('ClientSecret', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('users',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Username', sa.String(), nullable=True),
    sa.Column('Password', sa.String(), nullable=True),
    sa.Column('FirstName', sa.String(), nullable=True),
    sa.Column('LastName', sa.String(), nullable=True),
    sa.Column('Role', sa.String(), nullable=True),
    sa.Column('ExternalUsername', sa.String(), nullable=True),
    sa.Column('PaymentPlan', sa.Integer(), nullable=True),
    sa.Column('CreatedDateTime', sa.DateTime(), nullable=True),
    sa.Column('CompanyId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['CompanyId'], ['companies.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('events',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Title', sa.String(), nullable=True),
    sa.Column('CreatedBy', sa.Integer(), nullable=True),
    sa.Column('CreatedDateTime', sa.DateTime(), nullable=True),
    sa.Column('DateTimeFrom', sa.DateTime(), nullable=True),
    sa.Column('DateTimeTo', sa.DateTime(), nullable=True),
    sa.Column('Location', sa.String(), nullable=True),
    sa.Column('UserEmails', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['CreatedBy'], ['users.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('vaults',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(), nullable=True),
    sa.Column('CreatedBy', sa.Integer(), nullable=True),
    sa.Column('CreatedDateTime', sa.DateTime(), nullable=True),
    sa.Column('LastModifyDateTime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['CreatedBy'], ['users.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('collaborations',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('VaultId', sa.Integer(), nullable=True),
    sa.Column('UserId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['UserId'], ['users.Id'], ),
    sa.ForeignKeyConstraint(['VaultId'], ['vaults.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('folders',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(), nullable=True),
    sa.Column('CreatedBy', sa.Integer(), nullable=True),
    sa.Column('CreatedDateTime', sa.DateTime(), nullable=True),
    sa.Column('ParentId', sa.Integer(), nullable=True),
    sa.Column('VaultId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['CreatedBy'], ['users.Id'], ),
    sa.ForeignKeyConstraint(['ParentId'], ['folders.Id'], ),
    sa.ForeignKeyConstraint(['VaultId'], ['vaults.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('userevents',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('EventId', sa.Integer(), nullable=False),
    sa.Column('UserId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['EventId'], ['events.Id'], ),
    sa.ForeignKeyConstraint(['UserId'], ['users.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('files',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(), nullable=True),
    sa.Column('Path', sa.String(), nullable=True),
    sa.Column('FolderId', sa.Integer(), nullable=True),
    sa.Column('CreatedBy', sa.Integer(), nullable=True),
    sa.Column('CreatedDateTime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['CreatedBy'], ['users.Id'], ),
    sa.ForeignKeyConstraint(['FolderId'], ['folders.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('workspaces',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(), nullable=True),
    sa.Column('CreatedBy', sa.Integer(), nullable=True),
    sa.Column('CreatedDateTime', sa.DateTime(), nullable=True),
    sa.Column('LastModifyDateTime', sa.DateTime(), nullable=True),
    sa.Column('FolderId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['CreatedBy'], ['users.Id'], ),
    sa.ForeignKeyConstraint(['FolderId'], ['folders.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('pages',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(), nullable=True),
    sa.Column('WorkspaceId', sa.Integer(), nullable=True),
    sa.Column('CreatedBy', sa.Integer(), nullable=True),
    sa.Column('CreatedDateTime', sa.DateTime(), nullable=True),
    sa.Column('LastModifyDateTime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['CreatedBy'], ['users.Id'], ),
    sa.ForeignKeyConstraint(['WorkspaceId'], ['workspaces.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('tasks',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Title', sa.String(), nullable=True),
    sa.Column('Description', sa.String(), nullable=True),
    sa.Column('DueDate', sa.Date(), nullable=True),
    sa.Column('Status', sa.String(), nullable=True),
    sa.Column('Priority', sa.String(), nullable=True),
    sa.Column('Industry', sa.String(), nullable=True),
    sa.Column('AssignedTo', sa.Integer(), nullable=True),
    sa.Column('CreatedBy', sa.Integer(), nullable=True),
    sa.Column('CreatedDateTime', sa.DateTime(), nullable=True),
    sa.Column('LastModifyDateTime', sa.DateTime(), nullable=True),
    sa.Column('ParentId', sa.Integer(), nullable=True),
    sa.Column('PageId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['AssignedTo'], ['users.Id'], ),
    sa.ForeignKeyConstraint(['CreatedBy'], ['users.Id'], ),
    sa.ForeignKeyConstraint(['PageId'], ['pages.Id'], ),
    sa.ForeignKeyConstraint(['ParentId'], ['tasks.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('textbox',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Text', sa.Text(), nullable=True),
    sa.Column('CreatedBy', sa.Integer(), nullable=True),
    sa.Column('CreatedDateTime', sa.DateTime(), nullable=True),
    sa.Column('LastModifyDateTime', sa.DateTime(), nullable=True),
    sa.Column('PageId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['CreatedBy'], ['users.Id'], ),
    sa.ForeignKeyConstraint(['PageId'], ['pages.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('urls',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(), nullable=True),
    sa.Column('Url', sa.String(), nullable=True),
    sa.Column('CreatedBy', sa.Integer(), nullable=True),
    sa.Column('CreatedDateTime', sa.DateTime(), nullable=True),
    sa.Column('PageId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['CreatedBy'], ['users.Id'], ),
    sa.ForeignKeyConstraint(['PageId'], ['pages.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('favoritetasks',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('TaskId', sa.Integer(), nullable=True),
    sa.Column('UserId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['TaskId'], ['tasks.Id'], ),
    sa.ForeignKeyConstraint(['UserId'], ['users.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('pinnedtasks',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('TaskId', sa.Integer(), nullable=True),
    sa.Column('UserId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['TaskId'], ['tasks.Id'], ),
    sa.ForeignKeyConstraint(['UserId'], ['users.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pinnedtasks')
    op.drop_table('favoritetasks')
    op.drop_table('urls')
    op.drop_table('textbox')
    op.drop_table('tasks')
    op.drop_table('pages')
    op.drop_table('workspaces')
    op.drop_table('files')
    op.drop_table('userevents')
    op.drop_table('folders')
    op.drop_table('collaborations')
    op.drop_table('vaults')
    op.drop_table('events')
    op.drop_table('users')
    op.drop_table('companies')
    # ### end Alembic commands ###
