"""Remove PageId from Url, add FolderId

Revision ID: 5281dd1c3c25
Revises: 80ee85ee803a
Create Date: 2025-04-22 00:04:50.312870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5281dd1c3c25'
down_revision = '80ee85ee803a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('urls', schema=None) as batch_op:
        batch_op.add_column(sa.Column('FolderId', sa.Integer(), nullable=False))
        batch_op.drop_constraint('urls_PageId_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'folders', ['FolderId'], ['Id'])
        batch_op.drop_column('PageId')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('urls', schema=None) as batch_op:
        batch_op.add_column(sa.Column('PageId', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('urls_PageId_fkey', 'pages', ['PageId'], ['Id'])
        batch_op.drop_column('FolderId')

    # ### end Alembic commands ###
