"""add file upload fields and page association

Revision ID: 68e8d556dd53
Revises: 8d8c2cde4ffb
Create Date: 2025-08-11 15:30:24.991802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68e8d556dd53'
down_revision = '8d8c2cde4ffb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('AllDay')
        batch_op.drop_column('Frequency')
        batch_op.drop_column('Color')
        batch_op.drop_column('Description')

    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('FileData', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('FileSize', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('FileType', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('OrderIndex', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_column('OrderIndex')
        batch_op.drop_column('FileType')
        batch_op.drop_column('FileSize')
        batch_op.drop_column('FileData')

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Description', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Color', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Frequency', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('AllDay', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
