"""addo36file

Revision ID: 74329b6c6b82
Revises: f27f5d157d80
Create Date: 2025-05-22 23:33:58.353998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74329b6c6b82'
down_revision = 'f27f5d157d80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Iso265File', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_column('Iso265File')

    # ### end Alembic commands ###
