"""add image and paymentdatetime

Revision ID: 80ee85ee803a
Revises: ac928cf6cfac
Create Date: 2025-04-13 23:40:59.374453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80ee85ee803a'
down_revision = 'ac928cf6cfac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(), nullable=True),
    sa.Column('Base64Data', sa.Text(), nullable=True),
    sa.Column('PageId', sa.Integer(), nullable=True),
    sa.Column('CreatedBy', sa.Integer(), nullable=True),
    sa.Column('CreatedDateTime', sa.DateTime(), nullable=True),
    sa.Column('LastModifyDateTime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['CreatedBy'], ['users.Id'], ),
    sa.ForeignKeyConstraint(['PageId'], ['pages.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('PaymentDateTime', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('PaymentDateTime')

    op.drop_table('images')
    # ### end Alembic commands ###
