"""Files upload setup

Revision ID: 8d677b2f1266
Revises: 68e8d556dd53
Create Date: 2025-08-12 19:02:11.391361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d677b2f1266'
down_revision = '68e8d556dd53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_column('FileType')
        batch_op.drop_column('FileData')
        batch_op.drop_column('OrderIndex')
        batch_op.drop_column('FileSize')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('FileSize', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('OrderIndex', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('FileData', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('FileType', sa.VARCHAR(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
