"""Update models and event routes

Revision ID: a10fd0827a4b
Revises: f23a57c18c5f
Create Date: 2025-07-24 23:08:22.364516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a10fd0827a4b'
down_revision = 'f23a57c18c5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('AllDay', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('Frequency', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('Frequency')
        batch_op.drop_column('AllDay')

    # ### end Alembic commands ###
