"""add Card entity

Revision ID: a34483d8741b
Revises: 5195c1c8bf1a
Create Date: 2025-04-12 12:39:27.995504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a34483d8741b'
down_revision = '5195c1c8bf1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Description', sa.String(), nullable=True),
    sa.Column('Status', sa.String(), nullable=True),
    sa.Column('Priority', sa.String(), nullable=True),
    sa.Column('Category', sa.String(), nullable=True),
    sa.Column('DueDate', sa.Date(), nullable=True),
    sa.Column('AssignedTo', sa.Integer(), nullable=True),
    sa.Column('CreatedBy', sa.Integer(), nullable=True),
    sa.Column('CreatedDateTime', sa.DateTime(), nullable=True),
    sa.Column('LastModifyDateTime', sa.DateTime(), nullable=True),
    sa.Column('PageId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['AssignedTo'], ['users.Id'], ),
    sa.ForeignKeyConstraint(['CreatedBy'], ['users.Id'], ),
    sa.ForeignKeyConstraint(['PageId'], ['pages.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cards')
    # ### end Alembic commands ###
