"""add CreatedFromTask and CreatedFromTaskId to Workspace

Revision ID: ac6accb2a541
Revises: 3e6652213aba
Create Date: 2025-04-12 13:00:44.499987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac6accb2a541'
down_revision = '3e6652213aba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.add_column(sa.Column('CreatedFromTask', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('CreatedFromTaskId', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'tasks', ['CreatedFromTaskId'], ['Id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('CreatedFromTaskId')
        batch_op.drop_column('CreatedFromTask')

    # ### end Alembic commands ###
