"""add card_connections table

Revision ID: ac928cf6cfac
Revises: ac6accb2a541
Create Date: 2025-04-12 14:10:41.139916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac928cf6cfac'
down_revision = 'ac6accb2a541'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_connections',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('FromCardId', sa.Integer(), nullable=False),
    sa.Column('ToCardId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['FromCardId'], ['cards.Id'], ),
    sa.ForeignKeyConstraint(['ToCardId'], ['cards.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('card_connections')
    # ### end Alembic commands ###
