"""Add WorkspaceId to files table

Revision ID: add_workspace_id_to_files
Revises: fix_iso365_column_name
Create Date: 2025-08-12 23:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_workspace_id_to_files'
down_revision = 'fix_iso365_column_name'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('WorkspaceId', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'workspaces', ['WorkspaceId'], ['Id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('WorkspaceId')

    # ### end Alembic commands ###