"""addCardWorkSpace

Revision ID: ec5696a2261f
Revises: 2416717e32e6
Create Date: 2025-05-12 01:02:37.924518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec5696a2261f'
down_revision = '2416717e32e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.add_column(sa.Column('CreatedFromCardId', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'cards', ['CreatedFromCardId'], ['Id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('CreatedFromCardId')

    # ### end Alembic commands ###
