"""addPermissionType

Revision ID: f27f5d157d80
Revises: 0b241cb71c86
Create Date: 2025-05-12 21:47:39.996927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f27f5d157d80'
down_revision = '0b241cb71c86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collaborations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('PermissionType', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collaborations', schema=None) as batch_op:
        batch_op.drop_column('PermissionType')

    # ### end Alembic commands ###
