"""Fix Iso365File column name

Revision ID: fix_iso365_column_name
Revises: 8d677b2f1266
Create Date: 2025-08-12 20:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fix_iso365_column_name'
down_revision = '8d677b2f1266'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        # Rename column from Iso265File to Iso365File
        batch_op.alter_column('Iso265File', 
                             new_column_name='Iso365File',
                             existing_type=sa.Boolean(),
                             nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        # Rename column back from Iso365File to Iso265File
        batch_op.alter_column('Iso365File', 
                             new_column_name='Iso265File',
                             existing_type=sa.Boolean(),
                             nullable=True)

    # ### end Alembic commands ###